# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer\Osc_Freq.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(399, 300)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Full_Widg = QtWidgets.QFrame(Form)
        self.Full_Widg.setObjectName("Full_Widg")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Full_Widg)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Canvas = QtWidgets.QVBoxLayout()
        self.Canvas.setObjectName("Canvas")
        self.verticalLayout.addLayout(self.Canvas)
        self.Toggles = QtWidgets.QHBoxLayout()
        self.Toggles.setObjectName("Toggles")
        self.verticalLayout.addLayout(self.Toggles)
        self.horizontalLayout.addWidget(self.Full_Widg)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
