# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Player.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Full_Frame = QtWidgets.QFrame(Form)
        self.Full_Frame.setObjectName("Full_Frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Full_Frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Button_Frame = QtWidgets.QFrame(self.Full_Frame)
        self.Button_Frame.setObjectName("Button_Frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.Button_Frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Pause_Button = QtWidgets.QPushButton(self.Button_Frame)
        self.Pause_Button.setText("")
        self.Pause_Button.setObjectName("Pause_Button")
        self.horizontalLayout_3.addWidget(self.Pause_Button)
        self.Stop_Button = QtWidgets.QPushButton(self.Button_Frame)
        self.Stop_Button.setText("")
        self.Stop_Button.setObjectName("Stop_Button")
        self.horizontalLayout_3.addWidget(self.Stop_Button)
        self.Play_Button = QtWidgets.QPushButton(self.Button_Frame)
        self.Play_Button.setText("")
        self.Play_Button.setObjectName("Play_Button")
        self.horizontalLayout_3.addWidget(self.Play_Button)
        self.verticalLayout_2.addWidget(self.Button_Frame, 0, QtCore.Qt.AlignVCenter)
        self.Label_Frame = QtWidgets.QFrame(self.Full_Frame)
        self.Label_Frame.setObjectName("Label_Frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Label_Frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Time_Label = QtWidgets.QLabel(self.Label_Frame)
        self.Time_Label.setObjectName("Time_Label")
        self.verticalLayout.addWidget(self.Time_Label)
        self.verticalLayout_2.addWidget(self.Label_Frame, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.horizontalLayout.addWidget(self.Full_Frame, 0, QtCore.Qt.AlignVCenter)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Time_Label.setText(_translate("Form", "00:00 / 00:00"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
