# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Full_Layout = QtWidgets.QVBoxLayout()
        self.Full_Layout.setObjectName("Full_Layout")
        self.File_Button = QtWidgets.QPushButton(Form)
        self.File_Button.setObjectName("File_Button")
        self.Full_Layout.addWidget(self.File_Button)
        self.track_layout = QtWidgets.QHBoxLayout()
        self.track_layout.setObjectName("track_layout")
        self.Full_Layout.addLayout(self.track_layout)
        self.Synth_Button = QtWidgets.QPushButton(Form)
        self.Synth_Button.setCheckable(False)
        self.Synth_Button.setObjectName("Synth_Button")
        self.Full_Layout.addWidget(self.Synth_Button)
        self.verticalLayout_2.addLayout(self.Full_Layout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.File_Button.setText(_translate("Form", "New File"))
        self.Synth_Button.setText(_translate("Form", "Synthesize"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
